# Generated by Django 4.1.2 on 2022-12-20 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addurlentrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_link', models.CharField(max_length=250, verbose_name='Имя ссылки')),
                ('name_page', models.CharField(max_length=250, verbose_name='Имя страницы')),
                ('content_text', models.TextField(verbose_name='Информационный блок')),
            ],
            options={
                'verbose_name': 'Добавить страницу',
                'verbose_name_plural': 'Добавить страницу',
            },
        ),
    ]
