# Generated by Django 4.1.2 on 2022-12-20 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Technicalsupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя пользователя')),
                ('email', models.EmailField(max_length=200, verbose_name='Email')),
                ('messages', models.TextField(verbose_name='Сообщение пользователя')),
                ('date_time', models.DateTimeField(auto_now=True, verbose_name='Дата/Время обращения')),
            ],
            options={
                'verbose_name': 'панель обращения',
                'verbose_name_plural': 'панель обращения',
            },
        ),
    ]
