# Generated by Django 4.1.2 on 2022-12-20 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addnews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название')),
                ('text_news', models.TextField(verbose_name='Описание')),
                ('preview', models.ImageField(upload_to='news/%Y-%m-%d/', verbose_name='Превью')),
                ('date_time', models.DateTimeField(verbose_name='Дата/Время публикации')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новость',
            },
        ),
        migrations.CreateModel(
            name='Addimgnews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='news/%Y-%m-%d/', verbose_name='Изображение')),
                ('idnews', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appnewbecome.addnews')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображение',
            },
        ),
    ]
